name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Setup cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Configure application
      run: sh setup.sh
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Lint copypasta.py
      run: flake8 --config=tox.ini copypasta.py
    - name: Run tests
      run: python3 tests.py
